### ISSUE TITLE
r-forge to github transition

### ISSUE THREAD

**Issue by eddelbuettel** [cran-task-views/ctv#12]
### Steps done / left to do

Note that some repos listed below are private to this org unlike this meta repo used for the task list

- [x] keep copy of initial transfer as backup in [ctv-from-svn-2021-09](https://github.com/cran-task-views/ctv-from-svn-2021-09) (at r4134)
- [x] new transfer cut over today in [ctv-from-svn](https://github.com/cran-task-views/ctv-from-svn) (at r4248)

Repos already transferred manually:

- [x] Databases
- [x] Econometrics
- [x] ModelDeployment

Individual repos green-lit for transfer:

- [x] Bayesian
- [x] ChemPhys
- [x] Cluster
- [x] Environmetrics
- [x] ExperimentalDesign
- [x] Finance
- [x] FunctionalData
- [x] GraphicalModels
- [x] HighPerformanceComputing
- [x] MedicalImaging
- [x] MetaAnalysis
- [x] MissingData
- [x] NaturalLanguageProcessing
- [x] NumericalMathematics
- [x] OfficialStatistics
- [x] Optimization
- [x] Pharmacokinetics
- [x] Psychometrics
- [x] ReproducibleResearch
- [x] Spatial
- [x] Survival
- [x] TeachingStatistics
- [x] TimeSeries
- [x] Tracking

Individual repos ~on hold~ possibly needing extra work

- [x] ClinicalTrials
- [x] DifferentialEquations
- [x] Distributions
- [x] ExtremeValue
- [x] Genetics
- [x] Hydrology
- [x] MachineLearning
- [x] Phylogenetics
- [x] Robust
- [x] SpatioTemporal
- [x] WebTechnologies

/cc @zeileis

**Comment by zeileis** [comment]
Thanks, Dirk @eddelbuettel ! I have converted all of the old .ctv files to the new .md files, updated the contact/contribution details, added a README, entered GitHub meta-information, and posted a standardized issue about updating the task views and extending the maintainer team. If necessary, I modified the issue with some task-view-specific informations.

Most of the "green-lit" repositories should be on track, I think. For the others I have additionally sent personal e-mails to the maintainers, cc'ing all editors in most (but not all) cases. So let's see where this takes us in the next week or so.

I think we could close this general issue or would you track all of the follow-ups here as well?

P.S.: The September versions of the Bayesian and ChemPhys repositories are probably not needed anymore or would you still keep them?

**Comment by eddelbuettel** [comment]
Yes we can close this task now.   As for the older trials:  your call, feel free to remove all `*-2021-09` repos, or set them to private, or ... as you best see fit.  They were indeed temporary and should be subsumed within the new import(s).

**Comment by zeileis** [comment]
Thanks! I deleted the 2021-09 versions of the Bayesian and ChemPhys views which are definitely not needed anymore. The 2021-09 version of the converted svn I have kept for now...just in case it turns out to be useful.
