### ISSUE TITLE
Genetics task view orphaned

### ISSUE THREAD

**Issue by zeileis** [cran-task-views/ctv#17]
Giovanni Montana stepped down as the maintainer of the [Genetics](https://CRAN.R-project.org/view=Genetics) task view, hence I have flagged it as "Orphaned" with our e-mail contact in the new [source repository](https://github.com/cran-task-views/Genetics) (not public yet). It's a small task view which hasn't been updated in a while so many packages are missing, also including important ones like [poppr](https://CRAN.R-project.org/package=poppr) for example.

The question is where we go from here. We could try to look for a new group of maintainers. But possibly the scope of task view should be reconsidered in order to better avoid overlap with the [Phylogenetics](https://CRAN.R-project.org/view=Phylogenetics) task view. Another strategy could be to archive this old task view and encourage new proposals following the new workflow.

Any thoughts?
_Former maintainer:_ @gmontana
_CRAN Task View Editors:_ @rsbivand @eddelbuettel @rociojoo @davidjohannesmeyer @tuxette 
_Pyhlogenetics maintainer:_ @bomeara

**Comment by davidjohannesmeyer** [comment]
same for graphics. I would advocate for a general "call for taskviews" when we have an overview on what is (obviously) missing, so we can encourage concrete submissions.

**Comment by zeileis** [comment]
So you would be for archiving this on CRAN by now and having an open call later, right?

**Comment by tuxette** [comment]
I don't know if it is best to find a new maintainer now or to make an open call later but I read this task view a few weeks ago and I thought that: 1/ the task view could be enlarged to "Genetics and Genomics" instead of just "Genetics" and 2/ that it indeed needed an update.
I probably could suggest a few names (the topic is very close to or is exactly my area of expertise and work), if needed.

**Comment by zeileis** [comment]
I hoped you would say that, thanks Nathalie! But both points really indicate that the current task view should be archived and then we should encourage a new proposal in this area. But the precise title and scope should be reconsidered.

**Comment by zeileis** [comment]
Update:

* The Phylogenetics task view is also orphaned now as we could not get into touch with the maintainer. 
* Nathalie @tuxette suggested that both views, Genetics and Phylogenetics, could be merged.
* The current task views here on GitHub will remain "Private" and thus be archived when CRAN switches to the new workflow.
* Nathalie @tuxette will suggest some potential maintainers later on.

**Comment by tuxette** [comment]
Let me take a week or so to gather a few suggestions and I'll send them.

**Comment by zeileis** [comment]
Thanks!

**Comment by zeileis** [comment]
As Nathalie @tuxette has reached out to potential new maintainers for a merged/extended `Omics` task view. This will be proposed in a separate issue as a new task view. Hence I'm closing this issue here.

**Comment by tuxette** [comment]
Someone has already volunteered but I can put you in touch. @zeileis : What do you think?
