### ISSUE TITLE
Feature request: Enable `pkg()` and `bioc()` to cover other sources

### ISSUE THREAD

**Issue by billdenney** [cran-task-views/ctv#18]
As described here, `pkg()` covers CRAN, only.  And, for other sources (GitHub, bioconductor, and r-forge), other functions should be used.

https://github.com/cran-task-views/ctv/blob/445109a8e33cdbe0f1b3b70b9a6bd86488d05f67/Documentation.md?plain=1#L111-L115

For the Pharmacokinetics task view, one of the maintenance challenges in the past has been packages being archived and replaced on CRAN.  I have not tracked these changes in the past, and it's been harder to keep the view up to date.

I think it would be helpful if `pkg()` and `bioc()` were extended to cover the other sources (GitHub and r-forge) as arguments to the function.  And, when the task view is being built, if the package is not on CRAN (or bioconductor), then it would change to the backup repository.  That seems like it would lower the maintenance burden and point users to the most current/accurate source of information.

**Comment by zeileis** [comment]
The point of the CRAN task views is that they are actively maintained and mainly list resources on CRAN. This is why we don't want to fall back automatically on GitHub in that case. Often (albeit certainly not always) CRAN archival signals that a package is not actively maintained, that there are problems like failures of the code, sometimes even policy violations etc. Hence in these cases excluding the package from the task view is typically the right decision but, of course, sometimes it is useful to list the GitHub package instead. In any case, it is up to you as the maintainer to regularly look at these issue and update the task view as appropriate. This is also why we encouraged bringing co-maintainers on board to help with these tasks.
