### ISSUE TITLE
Finishing transition of task view projects

### ISSUE THREAD

**Issue by zeileis** [cran-task-views/ctv#19]
For a better overview of when we can launch the new workflow based on the Markdown files on CRAN, I created a task list here. It follows up on the discussion in Issue https://github.com/cran-task-views/ctv/issues/7.

You can check each item when the new task view .md files were sufficiently checked and adapted, the corresponding projects turned "Public", and included in the main [ctv/README.md](https://github.com/cran-task-views/ctv).

For tracking the progress and listing problems, please use the comments below.

- David @davidjohannesmeyer:
  - [x] Bayesian
  - [x] GraphicalModels
  - [x] NaturalLanguageProcessing
- Dirk @eddelbuettel
  - [x] Finance
  - [x] HighPerformanceComputing
- Nathalie @tuxette
  - [x] MedicalImaging
  - [x] MissingData
  - [x] Pharmacokinetics
  - [x] Survival
- Rocio @rociojoo
  - [x] DifferentialEquations
  - [x] ExperimentalDesign
  - [x] FunctionalData
  - [x] ReproducibleResearch
  - [x] Tracking
- Roger @rsbivand
  - [x] ChemPhys
  - [x] Environmetrics
  - [x] Spatial
  - [x] SpatioTemporal
  - [x] TeachingStatistics
- Achim @zeileis:  
  - [x] ClinicalTrials
  - [x] Cluster
  - [x] Databases
  - [x] Distributions
  - [x] Econometrics
  - [x] ExtremeValue
  - [x] Hydrology
  - [x] MachineLearning
  - [x] MetaAnalysis
  - [x] ModelDeployment
  - [x] NumericalMathematics
  - [x] OfficialStatistics
  - [x] Optimization
  - [x] Psychometrics
  - [x] Robust
  - [x] TimeSeries
  - [x] WebTechnologies
- Orphaned:
  - [x] Genetics
  - [x] Phylogenetics

**Comment by zeileis** [comment]
As the maintainer of the "Phylogenetics" task view was not responsive over the last 3 months, I have orphaned the task view now. This means that: (a) repository remains "Private", (b) maintainer is "Orphaned", (c) e-mail is CRAN-Task-Views@R-project.org.

The orphaned task views will not be released on CRAN when we switch to the new workflow.

Should we try to actively find a new maintainer for "Phylogenetics"? Or should we wait what we will end up doing with the "Genetics" task view (see issue https://github.com/cran-task-views/ctv/issues/17)? It might make sense to decide this together. What do you think @tuxette ?

**Comment by zeileis** [comment]
David @davidjohannesmeyer & Dirk @eddelbuettel , I have just checked the task views in your to-do list. It seems that you didn't try to remind the maintainers, yet, did you? If not, I would recommend that you write a follow-up comment to the maintainers (and @ them directly) in the first issue that is still open. Thanks!

**Comment by tuxette** [comment]
Achim @zeileis : for me, it would make sense to merge this two task views (Genetics and Phylogenetics) and to search for fresh maintainers.

**Comment by zeileis** [comment]
OK, good, I've made a corresponding follow-up comment in issue https://github.com/cran-task-views/ctv/issues/17 and will flag the two items as "done" here on the task list.

**Comment by davidjohannesmeyer** [comment]
> David @davidjohannesmeyer & Dirk @eddelbuettel , I have just checked the task views in your to-do list. It seems that you didn't try to remind the maintainers, yet, did you? If not, I would recommend that you write a follow-up comment to the maintainers (and @ them directly) in the first issue that is still open. Thanks!

Done, and also sent mails directly.

**Comment by zeileis** [comment]
Thanks, David!

**Comment by zeileis** [comment]
All task views (except the two orphaned ones) are now public and should be in good enough shape to be included in the new CRAN workflow. Hence I'm closing this issue here.

Hopefully we will finally switch to the new workflow next week.
