### ISSUE TITLE
Checking/feedback for new technical documentation

### ISSUE THREAD

**Issue by zeileis** [cran-task-views/ctv#2]
I have written technical documentation that explains how to write the new task view documents in R/Markdown format (including information on how to convert the legacy XML format). See: [Documentation](../blob/main/Documentation.md)

Personally I'm quite happy about it but I would appreciate your feedback on this, too. Please read the documentation and check the task list if you think the documentation is good to go. If you think that improvements are needed feel free to make changes in the file directly or discuss them below.

- [x] @davidjohannesmeyer 
- [x] @eddelbuettel 
- [x] @rociojoo 
- [x] @rsbivand 
- [x] @tuxette 

_(Heather, I haven't listed you explicitly because I asked you already for creating the code of conduct. If you can provide feedback on this issue as well, this is of course more than welcome.)_

**Comment by rociojoo** [comment]
Achim @zeileis sorry for the delay. This version looks great. The only thing I would add for a next version of the vignette of the `ctv` package would be a note indicating that `priority = core` should only be added the first time you refer to a package. If I do it every time I mention the package it all goes wrong and end up with a large list of core packages.

**Comment by zeileis** [comment]
That was a bug in `read.ctv()`, thanks for spotting this. I just fixed it in the SVN on R-Forge. When r4245 of the `ctv` package (<https://R-Forge.R-project.org/R/?group_id=39>) has been rebuilt on R-Forge, you can reinstall the package and everything should work smoothly then.
