### ISSUE TITLE
Visibility of CRAN Task Views on r-project.org

### ISSUE THREAD

**Issue by tappek** [cran-task-views/ctv#23]
Dear CRAN Task View Editors,

Thank you so much for the effort you put into revamping the approach to the Task Views!

Maybe one thing we could think about is how to advertise the CRAN Task Views more prominently on r-project.org. The news entry on the landing page and the Twitter announcements are great. However, they are rather temporary measure and I feel like the CRAN Task Views almost go unnoticed by website visitors.

Here are to two ideas for r-project.org (rather minor, I admit):
* https://cloud.r-project.org/web/packages/index.html: Here, the Task Views are mentioned in section "Installation of Packages". I think they would be better placed in the top section "Available Packages" (as last point). Furthermore, more context for the Task Views could be given there to underpin their usefulness. I have the intro section contained in each Task View in mind (stripped by the installation hint), i.e., _CRAN task views aim to provide some guidance which packages on CRAN are relevant for tasks related to a certain topic. They give a brief overview of the included packages. The views are intended to have a sharp focus so that it is sufficiently clear which packages should be included (or excluded) - and they are not meant to endorse the "best" packages for a given task._

* In the navigation frame (https://cloud.r-project.org/navbar.html), the Task Views are currently under section "CRAN", but I feel like they would be better placed under section "Software", right after "Packages".

(An unrelated note about https://cloud.r-project.org/web/packages/index.html: The link to Windows check summary is broken.)

**Comment by zeileis** [comment]
Thanks for the suggestions, Kevin @tappek ! I've notified the CRAN team, let's see what they think. The suggestions for the packages index page are good and straightforward, I think. I'm not sure whether they agree about the navbar.

**Comment by zeileis** [comment]
All incorporated now by the CRAN team. Thanks again!

**Comment by zeileis** [comment]
More issues like this are always welcome!
