### ISSUE TITLE
syntax for `function::pkg`?

### ISSUE THREAD

**Issue by bbolker** [cran-task-views/ctv#33]
Is there a recommended syntax/markup for referring to a particular function within a package? (The use case is that for mixed models, there are several cases where there is a single/particular function within a package that is relevant, e.g. `MASS::glmmPQL`)

**Comment by zeileis** [comment]
There is no dedicated `ctv`-specific syntax for this at the moment. So you can just use backticks for `glmmPQL` or `MASS::glmmPQL` in addition to mentioning `r pkg("MASS")` somewhere in the same paragraph. The latter then records the package as part of the task view and creates the hyperlink.
