### ISSUE TITLE
HTML anchors

### ISSUE THREAD

**Issue by bbolker** [cran-task-views/ctv#36]
At the moment `[text]{anchorname}` works to denote an anchor within the document and `[text](#anchorname)` links to it, but according to [StackOverflow](https://stackoverflow.com/questions/5319754/cross-reference-named-anchor-in-markdown) this is a markdown extension and is back-end-dependent.

Is it safe/advisable to use this format for anchors in task views?

**Comment by zeileis** [comment]
Yes, that's ok. You can try out whether it works via `ctv2html()` which processes the Markdown part with `pandoc` and this supports such anchors.

Also note that it may not be necessary to set the anchors explicitly. Namely when you want to refer to a section `Section title` you can simply use `#section-title`.

**Comment by bbolker** [comment]
Thanks. I can see that this works at present, but wanted to make sure you weren't contemplating changes in the back-end that would make it stop working ...

In the case I'm thinking of I wanted to redirect users to a point in the document that was **not** indicated by a section head (it's part of a bulleted list, below section headers in the hierarchy).

**Comment by zeileis** [comment]
Yes, thanks for checking with us, this is fine!
