### ISSUE TITLE
CRAN task view proposal: AutoML

### ISSUE THREAD

**Issue by neerajdhanraj** [cran-task-views/ctv#37]
### Scope

This CRAN Task View proposal contains a list of packages useful for Automated Machine Learning tools and processes. These packages are related to packages that automate:

- a) the modeling (parameter tuning) of methods/models for data analysis,
- b) performance evaluation, and comparative analysis,
- c) effective visualization, and
- d) other aspects of AutoML tools. 

This CRAN task view is a review the progress in AutoML tools based on different categories including time series analysis, forecasting, predictions, data cleaning (e.g., missing value imputations, outlier detections), classifications, complexity, and visualization, along with the packages for data analysis models that autotune their parameters based on the nature of the dataset. The focus is on collecting all automated machine learning-related packages on one platform, where gaps and potential in AutoML research domain can be explored. This collection is helpful for researchers and data scientists researching in automation in Machine Learning (and Data Science). 

This task view aims at assisting users from novice to advanced levels and promoting R in AutoML field. Also, it is aimed to include all possible research directions in AutoML in this CRAN Task View and cluster the relevant packages at appropriate categories at regular intervals.

### Packages:
Some example of the packages include the following:
[automl](https://cran.r-project.org/package=automl)
[RemixAutoML](https://github.com/AdrianAntico/RemixAutoML)
[autoxgboost](https://github.com/ja-thomas/autoxgboost)
[forester](https://github.com/ModelOriented/forester)
[lares](https://cran.r-project.org/package=lares)
[ForecastTB](https://cran.r-project.org/package=ForecastTB)
[cleanTS](https://cran.r-project.org/package=cleanTS)
[imputeTestbench](https://cran.r-project.org/package=imputeTestbench)
[GuessCompx](https://github.com/agenis/GuessCompx)
[forecast](https://cran.r-project.org/package=forecast)
[auto.pca](https://cran.r-project.org/package=auto.pca)
[groupdata2](https://cran.r-project.org/package=groupdata2)
[autoTS](https://cran.r-project.org/package=autoTS)
[autostats](https://cran.r-project.org/package=autostats)
[prophet](https://cran.r-project.org/package=prophet)
[automap](https://cran.r-project.org/package=automap)
[PSF](https://cran.r-project.org/package=PSF)

### Overlap
There is minimal overlap with other CRAN task views as described below:
[MachineLearning](https://github.com/cran-task-views/MachineLearning/) focuses on a very broad area of Machine Learning and did not explicitly speak about the AutoML tools and processes. 

### Maintainers
Neeraj Dhanraj Bokde (neerajdhanraj@gmail.com/neerajdhanraj@qgg.au.dk)
**Note:** Interested UserRs are welcome to the Maintainers' list.

**Comment by zeileis** [comment]
Thanks for the proposal!

I think in the current form this should rather be a new section in the existing `MachineLearning` task view rather than a separate new task view. However, given that we talked with @thothorn about potentially splitting up the task view, I'm pinging him here for his thoughts.

**Comment by thothorn** [comment]
I think it would be good to start a dedicated task view (ML is already too broad).

**Comment by zeileis** [comment]
OK, thanks for the feedback. Could you maybe elaborate on what you think inclusion/exclusion criteria should be? I.e., when is a package sufficiently "auto" to go into AutoML, when is it "normal" MachineLearning, and in which cases is a duplicated listing warranted. Note that we would need something that would not just work for separating the status quo but also future packages to come.

**Comment by mitokic** [comment]
I think the [finnts](https://cran.r-project.org/package=finnts) package would be a great addition to the AutoML/ML/timeseries/finance task view. It's Microsoft finance's automated time series forecasting framework.

**Comment by rociojoo** [comment]
@neerajdhanraj Just pinning to know if you're still keen on this proposal. If so, could you address @zeileis 's question?

**Comment by tuxette** [comment]
No feedback so far so I am closing this issue now.
