### ISSUE TITLE
could ctv::install.views skip previously installed packages?

### ISSUE THREAD

**Issue by bbolker** [cran-task-views/ctv#38]
As far as I can tell `ctv::install.views()` installs packages even if they have already been installed (i.e., it simply calls `install.packages()` on all of the listed packages from a task view). Is there any reason *not* to have it check against/exclude packages that already exist in `rownames(installed.packages())` ... ??

**Comment by zeileis** [comment]
That's what `ctv::update.views()` does. It additionally checks whether the version on CRAN is newer than the one installed.
