### ISSUE TITLE
Sufficient to mention priority = "core" once?

### ISSUE THREAD

**Issue by wviechtb** [cran-task-views/ctv#39]
Just a question about the use of `priority = "core"`: Is it sufficient to use this once for a core package that might be mentioned in several places or should this be repeated every time the package is listed?

**Comment by zeileis** [comment]
Yes, indeed. I will add this to the docs.

**Comment by jpiaskowski** [comment]
I just checked: when a package is mentioned without `priority = "core"`, it will not show up in the list of 'core' packages at the bottom of the CTV even if it is also listed as "core" in another section of the CTV (although perhaps it is still installed via the CTV package?).

**Comment by zeileis** [comment]
Did you try this with `ctv` version 0.9-4? Either from R-Forge (where the code was improved since April) or CRAN (released in response to Wolfgang's message above).

**Comment by wviechtb** [comment]
As far as I can tell, it's working as intended. I updated the meta-analysis task view two days ago and the core packages are designed as such only once and they show up correctly.

**Comment by zeileis** [comment]
Good, thanks for the feedback!

**Comment by jpiaskowski** [comment]
sorry, I should have updated my CTV package before testing.

**Comment by zeileis** [comment]
No worries, I should have released `ctv` 0.9-4 to CRAN a while ago... But it's good that the package and the documentation have been updated now!
