### ISSUE TITLE
CRAN task view proposal: VisualizationStatic

### ISSUE THREAD

**Issue by dicook** [cran-task-views/ctv#45]
The Graphics CTV was archived several years ago because it wasn't sufficiently maintained, and there were way too many packages listed. It needed to be broken into smaller subsets. This is a proposal for creating several new CTVs covering the vast range of graphics capabilities in R.

# Scope  

This CTV summarizes the static graphics packages available on CRAN. Graphics capabilities is one of the strengths of R, and it is important to have an active summary available for users. 

## Inclusion criteria 

Package provides tools for drawing visual displays of data. 

## Exclusion criteria 

The graphics are not interactive (direct manipulation) by default, e.g. the user cannot click on an element and have a label pop-up. It is not a low level graphics device upon which many drawing packages are rendering to screen or file. 

# Packages

See the draft web site at https://github.com/dicook/ctv-visualizationstatic. 

# Overlap 

There is no overlap with existing CTVs. We are also proposing that new CTVs are written: VisualizationDynamic which will list packages with interactive and dynamic capabilites. ColorPalettes will list the large array of different colour palettes available with different drawing systems. GraphicsDevices will list the variety of devices to draw graphics on the screen or output to file.

# Maintainers

Di Cook and Sherry Zhang

**Comment by zeileis** [comment]
Thanks, Di @dicook and Sherry @huizezhang-sherry, for taking action and proposing new task views to fill the gap that the retirement of the old Graphics task view left. I fully agree that the only chance we have to cover the vast range of graphical tools in R is to break things down into more manageable portions. Some of your suggestions could work well, I think, but I'm not so sure about this particular one.

Your inclusion criteria say: _Package provides tools for drawing visual displays of data._ From the draft of the task view it seems that you mean this at a rather low level, i.e., functionality for setting up coordinate systems, drawing points and lines, etc. while statistical graphics are excluded. First, I'm not sure how easy it is "draw the line" between the technical infrastructure and its applications. And just referring to lists of packages elsewhere (as with the ggplot2 extensions) is probably not the best solution either. Second, from the name `VisualizationStatic` most readers would probably expect something else.

**Comment by dicook** [comment]
We debated names for the CTV. A reason to use Visualisation is that this is more commonly searched, and it is less likely to be confused with GraphicalModels. Having the different CTVs close to each other in name should make it easier for users to see them.

Happy to expand on the inclusion criteria.

**Comment by zeileis** [comment]
Regarding the name: I would then flip the order (`StaticVisualizations` rather than `VisualizationStatic`) because I find it more important that the name is easy to understand by itself. But I let the other task view editors weigh in here.

Regarding the inclusion criteria: The question is what is a good expansion here that does not encompass several hundred packages that include some kind of plotting function.

**Comment by tuxette** [comment]
Thanks @dicook  and @zeileis for the proposal and first assessment. My two cents:
- regarding the name, I would also prefer `StaticVisualizations` (and indeed, `GraphicalModels` refers to something else for me); 
- regarding the scope and current content, as Achim already commented, I am not sure where to draw the line but I think that the current version is a bit restrictive at the moment. Most of the packages that are cited are already very well known by the R community and I would expect a bit more of a TV. Similarly to the `DynamicVisualization` TV for instance, I think that including sections related to some specific visualization tasks (like graphs/networks or time series or missing data or maps or ...) sound like a minimum desirable addition to me;
- this would also probably be good to invite other people to contribute. You could try with https://www.linkedin.com/in/cbontemps/ (I can give his direct email in private message) or @cregouby who are both active members of the dataviz and R communities.

**Comment by cregouby** [comment]
Great initiative !
I'll be glad to contribute.

**Comment by rociojoo** [comment]
Thanks @dicook and @huizezhang-sherry. I agree with @zeileis and @tuxette about `StaticVisualizations` rather than `VisualizationStatic`. And I think you can mention the `DynamicVisualizations` TV in this TV and vice-versa. 

I can understand that adding sections on specific visualization tasks could be challenging to maintain. Some of them are already mentioned in their corresponding TV (e.g. time series, spatial), so I suggest guiding readers to those TVs.

**Comment by zeileis** [comment]
Thanks again, Di @dicook and Sherry @huizezhang-sherry, for your proposal. Unfortunately, we did not have any follow-up (except for some discussion of the name). Should we close this issue now or do you want to continue working on it? I think the fundamental issue is finding some inclusion/exclusion criteria that will yield a task view that is (a) not too huge and maintainable for you but still (b) covers packages that most readers/users will be interested in. Just including the infrastructure packages and then referring to lists of graphics/visualization packages elsewhere is not a good solution, I think.

**Comment by dicook** [comment]
We would like to continue working on this when semester finishes


> On 4 Oct 2023, at 5:56 pm, Achim Zeileis ***@***.***> wrote:
> 
> 
> Thanks again, Di @dicook and Sherry @huizezhang-sherry, for your proposal. Unfortunately, we did not have any follow-up (except for some discussion of the name). Should we close this issue now or do you want to continue working on it? I think the fundamental issue is finding some inclusion/exclusion criteria that will yield a task view that is (a) not too huge and maintainable for you but still (b) covers packages that most readers/users will be interested in. Just including the infrastructure packages and then referring to lists of graphics/visualization packages elsewhere is not a good solution, I think.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

cheers,
Di


---
Dianne Cook
***@***.***

**Comment by zeileis** [comment]
OK, good, then we will keep this issue open.

Possibly it would be a good idea to first finish the "DynamicVisualizations" task view from https://github.com/cran-task-views/ctv/issues/46, which will be easier, and then revisit the "StaticVisualizations"?

**Comment by zeileis** [comment]
Given that #46 is completed now, maybe you could revisit this proposal as well?

**Comment by zeileis** [comment]
Thanks again, Di @dicook and Sherry @huizezhang-sherry, for the initiative and your work so far. Given that there was no follow-up (except discussion of the name and some technical aspects), I'm closing this issue now. If you are still interested in setting up a task view on static visualizations, we would still welcome a new proposal in the future. If so, please reconsider the scope and include further co-maintainers. Regarding the scope the main issue is to define good inclusion/exclusion criteria that yield those packages that readers would likely be interested in without making the list too large.
