### ISSUE TITLE
CRAN task view proposal: VisualizationDynamic

### ISSUE THREAD

**Issue by dicook** [cran-task-views/ctv#46]
The Graphics CTV was archived several years ago because it wasn't sufficiently maintained, and there were way too many packages listed. It needed to be broken into smaller subsets. This is a proposal for creating several new CTVs covering the vast range of graphics capabilities in R.

# Scope  

This CTV summaries the dynamic graphics packages available on CRAN. Dynamic graphics have historically been available in R, but new packages are emerging regularly, particularly as new technology emerges. It is important to have an active summary available for users.

## Inclusion criteria 

Package provides tools for drawing visual displays of data, that have some interactive (direct manipulation) or dynamic component. For example, the user can click on an element and have a label pop-up, or the plots are rapidly updated to produce a rotation or animation.

## Exclusion criteria 

he graphics are not primarily interactive or dynamic. It is not a low level graphics device upon which many drawing packages are rendering to screen or file.

# Packages

See the draft web site at https://github.com/dicook/ctv-visualizationdynamic. 

# Overlap 

There is a small amount of overlap with Spatial CTV, for interactive mapping. We are also proposing that new CTVs are written: VisualizationDynamic which will list packages with interactive and dynamic capabilites. ColorPalettes will list the large array of different colour palettes available with different drawing systems. GraphicsDevices will list the variety of devices to draw graphics on the screen or output to file.

# Maintainers

Di Cook and Jayani Lakshika

**Comment by zeileis** [comment]
As already mentioned in https://github.com/cran-task-views/ctv/issues/45 thanks for the effort, very much appreciated. For this proposal the scope is much clearer, I think, with clear inclusion and exclusion criteria. And the overlap with the spatial task view is not huge and can probably be improved when this task view takes more concrete shape.

I mainly don't like the title. Wouldn't `DynamicGraphics` be a bit easier?

**Comment by dicook** [comment]
We debated names for the CTV. A reason to use Visualisation is that this is more commonly searched, and it is less likely to be confused with GraphicalModels. Having the different CTVs close to each other in name should make it easier for users to see them. (Same comment as in the [#45](https://github.com/cran-task-views/ctv/issues/45)).

**Comment by rociojoo** [comment]
Thank you @dicook As in #45 , I think that `DynamicVisualizations` would be a more informative name, and mentioning the `StaticVisualizations` TV here would make it easier for users to access it.

**Comment by zeileis** [comment]
Di @dicook, Jayani @JayaniLakshika, and Sherry @huizezhang-sherry, thanks again for your proposal. Unfortunately, we did not have any follow-up except for the short discussion of the name. But I still think that this would be a nice contribution which mainly needs to be worked out. If you are still interested in doing so:

- Please change the name to `DynamicVisualizations`.
- Work out the text.
- Include some comments regarding the scope of the task view in its introduction (especially that packages providing graphics devices are not included, etc.).
- The section with the further resources at the end should be turned into the standard `### Links` section, see the [documentation](https://github.com/cran-task-views/ctv/blob/main/Documentation.md).
- Please drop the anchors you have added manually and instead use the ones that `rmarkdown`/`pandoc` will add automatically. For example, instead of `## [Small multiples]{#multiples}` you can just use `## Small multiples` (without additional markup) and refer to it using `#small-multiples` (lower case, hyphens instead of spaces) in the table of contents.

**Comment by dicook** [comment]
Happy to make these changes

> On 4 Oct 2023, at 6:10 pm, Achim Zeileis ***@***.***> wrote:
> 
> 
> Di @dicook, Jayani @JayaniLakshika, and Sherry @huizezhang-sherry, thanks again for your proposal. Unfortunately, we did not have any follow-up except for the short discussion of the name. But I still think that this would be a nice contribution which mainly needs to be worked out. If you are still interested in doing so:
>     • Please change the name to DynamicVisualizations.
>     • Work out the text.
>     • Include some comments regarding the scope of the task view in its introduction (especially that packages providing graphics devices are not included, etc.).
>     • The section with the further resources at the end should be turned into the standard ### Links section, see the documentation.
>     • Please drop the anchors you have added manually and instead use the ones that rmarkdown/pandoc will add automatically. For example, instead of ## [Small multiples]{#multiples} you can just use ## Small multiples (without additional markup) and refer to it using #small-multiples (lower case, hyphens instead of spaces) in the table of contents.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

cheers,
Di


---
Dianne Cook
***@***.***

**Comment by dicook** [comment]
Changes have been made and are now at https://github.com/dicook/ctv-dynamicvisualizations

**Comment by tuxette** [comment]
Thanks @dicook for the nice proposal! I had a quick look at it and I add a few suggestions:

- for me, the difference and purpose of the sections "General purpose", "Infrastructure", and "rgl additions" is not perfectly clear and, more specifically, in the last section "rgl additions", I am not sure about what differentiates the last suggestion `predicts3D` from a general tool for visualization of regression models (why is it in "RGL"?);

- the following packages might be interesting to consider as well: `iplots`, `ggvis`, `rCharts`, ` rbokeh`, `heatmaply`, `collapsibleTree`, `dygraphs`, `magick`;

- the descriptions of packages are not always homogeneous: sometimes, you have the package name, then a pipe and a description and some other times, you have the package name, then "for" and a description. Also, description are either:

> `r package("ggiraph")` | adopts ggplot syntax for interactive graphics.

(sentence starting with the package name)

> `r package("highcharter")` | R binding to the general purpose highchart JavaScript library.

(not a sentence, just a description). I think that descriptions could be made a bit longer and more detailed than the current version (this might be the suggestion of @zeileis when he said "Work out the text."?);

- finally, the syntax for packages in ctv is either `r pkg("blabla")` or `r bioc("blabla")` or the alternative forms listed in https://cran.r-project.org/web/packages/ctv/vignettes/ctv-howto.html . Please, use `ctv::ctv2html(...)` to check the final form of the TV and also `ctv::check_ctv_packages(...)` to check that all packages are properly listed.

**Comment by zeileis** [comment]
Thanks Di @dicook for the update and Natalie @tuxette for the feedback. This already much improved and heading in the right direction. But the text is still too terse and too heterogeneous (as pointed out in more detail by Nathalie).

Also, I think it would be important to give a bit of an overview of the different infrastructures that are leveraged for making the graphics dynamic. Then it is easier to understand the structure of the table of contents and to understand some reoccurring terms (such as "OpenGL" or "D3" for example).

Please flag some packages as "core" packages as well.

**Comment by dicook** [comment]
We’re working on it!

> On 8 Jan 2024, at 10:13 am, Achim Zeileis ***@***.***> wrote:
> 
> 
> Thanks Di @dicook for the update and Natalie @tuxette for the feedback. This already much improved and heading in the right direction. But the text is still too terse and too heterogeneous (as pointed out in more detail by Nathalie).
> Also, I think it would be important to give a bit of an overview of the different infrastructures that are leveraged for making the graphics dynamic. Then it is easier to understand the structure of the table of contents and to understand some reoccurring terms (such as "OpenGL" or "D3" for example).
> Please flag some packages as "core" packages as well.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

cheers,
Di


---
Dianne Cook
***@***.***

**Comment by dicook** [comment]
@zeileis I think that the CTV has all the changes requested now.

**Comment by tuxette** [comment]
Hi @dicook : I quickly checked it today and I think that the requested changes have indeed been made. Thanks a lot! I think that it is publishable as is if other CTV board members endorse it: what do you think @zeileis ? 
Of note (minor): some of the files currently versioned will have to be removed before final publication (at least `.DS_Store` and the HTML version `DynamicVisualizations.html`).

**Comment by zeileis** [comment]
Apologies for the long delay and thank you for the thorough update, Di @dicook and Sherry @huizezhang-sherry! The task view looks great now and is good to go.

I just suggest to use a longer "topic" title and I've made various small improvements in a PR I sent you: https://github.com/dicook/ctv-dynamicvisualizations/pull/5

Please handle the PR and afterwards transfer your repository to me:

> Settings > Collaborators > Public Repository > Manage

and then

> Danger Zone > Transfer ownership

to "zeileis".

Then I can transfer the repository  to the `cran-task-views` organization and handle all subsequent steps.

**Comment by dicook** [comment]
I get an error when I try to transfer ownership:

zeileis already has a repository in the dicook/ctv-dynamicvisualizations network

I think you need to remove your fork @zeileis

> On 23 Sep 2024, at 6:56 AM, Achim Zeileis ***@***.***> wrote:
> 
> 
> Apologies for the long delay and thank you for the thorough update, Di @dicook and Sherry @huizezhang-sherry! The task view looks great now and is good to go.
> I just suggest to use a longer "topic" title and I've made various small improvements in a PR I sent you: dicook/ctv-dynamicvisualizations#5
> Please handle the PR and afterwards transfer your repository to me:
> Settings > Collaborators > Public Repository > Manage
> and then
> Danger Zone > Transfer ownership
> to "zeileis".
> Then I can transfer the repository to the cran-task-views organization and handle all subsequent steps.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

cheers,
Di


---
Dianne Cook
***@***.***

**Comment by zeileis** [comment]
Thanks, Di. I have deleted my fork now, please try again.

**Comment by zeileis** [comment]
OK, transition complete, CRAN release done, social media posts out :tada: 

- https://fosstodon.org/@zeileis/113197929131832868
- https://bsky.app/profile/zeileis.org/post/3l4xzv3n5tt2x
- https://x.com/AchimZeileis/status/1838902936975425714
