### ISSUE TITLE
CRAN task view proposal: ColorPalettes

### ISSUE THREAD

**Issue by dicook** [cran-task-views/ctv#47]
The Graphics CTV was archived several years ago because it wasn't sufficiently maintained, and there were way too many packages listed. It needed to be broken into smaller subsets. This is a proposal for creating several new CTVs covering the vast range of graphics capabilities in R.

# Scope

This CTV will provide a list of available colour palettes in R packages, and resources on choosing appropriate palettes. 

# Packages

- paletteer | Collects all color palettes across R
- RColorBrewer | Color schemes for maps (and other graphics)
- wesanderson | Palettes generated mostly from 'Wes Anderson' movies
- viridis | Color maps that improve readability for readers with common forms of color blindness and/or color vision deficiency
- palettetown | Pokemon(R) inspired palettes with additional 'ggplot2' scales
- RImagePalette | Extracts the dominant colors from an image, and turns them into a scale for use in plots
- PNWColors | PNW-Inspired Palettes
- imgpalr | Create color palettes from image files. Offers control over the type of color palette to derive (qualitative, sequential or divergent) and other palette properties.
- nic | Color palettes based on nature inspired colours in "Sri Lanka"
- ggsci | A collection of 'ggplot2' color palettes inspired by plots in scientific journals, data visualization libraries, science fiction movies, and TV shows
- rainbow | 
- ggprism | Themes, palettes, and other functions used to customise ggplots to look like they were made in 'GraphPad Prism'
- colorspace | Mapping between assorted color spaces including RGB, HSV, HLS, CIEXYZ, CIELUV, HCL (polar CIELUV), CIELAB, and polar CIELAB. Qualitative, sequential, and diverging color palettes based on HCL colors are provided.
- rcartocolor | Color schemes for maps and other graphics designed by 'CARTO' 
- scico | Perceptually uniform and colour-blindness friendly palettes developed by Fabio Crameri and released under the "Scientific Colour-Maps" moniker
- palettes | A comprehensive library for colour vectors and colour palettes using a new family of colour classes (palettes_colour and palettes_palette) that always print as hex codes with colour previews
- ggthemes | Some extra themes, geoms, and scales for 'ggplot2'
- jcolors | A selection of color palettes and 'ggplot2' themes designed by the package author
- nord | Arctic Ice Studio's Nord and Group of Seven inspired colour palettes for 'ggplot2'
- oompaBase | 
- palr | Colour palettes for data, based on some well known public data sets
- pals | Color Palettes, colormaps, and tools to evaluate them
- Redmonder | Microsoft(r)-Inspired Color Palettes
- ghibli | Colour palettes inspired by Studio Ghibli films
- Polychrome | Qualitative palettes with many (20-30 or more) colors 

# Overlap

There is no overlap with current CTVs.

# Maintainers

Di Cook and Emil Hvitfeldt

**Comment by zeileis** [comment]
Thanks, Di @dicook and Emil @EmilHvitfeldt, for this proposal. I think that a color-related task view would be a very useful addition but why feeling is that "color palettes" is maybe too narrow.

With packages like `paletteer` and `pals` we already cover a very wide range of palettes consisting of sets of hex codes. Hence my feeling is that we don't need a task view that lists every package which has extracted such sets of hex codes from some movies, paintings, photos, etc. Instead there might be more interest in packages that allow the creation of custom palettes, modifying existing ones, assessing their suitability in different contexts, combining them with different graphics packages, etc.

You might also get in touch with Olivier Eterradossi (`olivier.eterradossi at mines-ales.fr`, [LinkedIn](https://www.linkedin.com/pub/dir/olivier/eterradossi)) who had expressed interest in setting up a color task view some years ago. Eventually it didn't come together but he might be willing to contribute to this initiative.

Another person who might have valuable inputs is Martijn Tennekes who recently set up [cols4all](https://CRAN.R-project.org/package=cols4all) and worked quite a bit on assessing different palettes.

Two other small comments:

* [MetBrewer](https://CRAN.R-project.org/package=MetBrewer) is another package that provides a quite nice list of art-based palettes.
* I think the `rainbow` package does not provide any packages itself but leverages the palettes from other packages.

**Comment by rociojoo** [comment]
Thanks @dicook and @EmilHvitfeldt. I didn't know there were so many color palette packages! 
I agree with @zeileis that a color TV would be more useful, and perhaps doable if you work with the people Achim mentioned. It depends of course on whether you'd be motivated to do so.

**Comment by zeileis** [comment]
Thanks again, Di @dicook and Emil @EmilHvitfeldt, for the initiative and your work so far. Given that there was no follow-up, I'm closing this issue now. If you are still interested in setting up a color-related task view we would be very happy to receive a new proposal. If so:

- Please propose a broader "Color" task view, not just focusing on palettes but including packages with more general color functionality (see my feedback above).
- Please suggest some more possible co-maintainers who could bring in some different background/expertise (see also my suggestions above).
