### ISSUE TITLE
CRAN task view proposal: GraphicsDevices

### ISSUE THREAD

**Issue by dicook** [cran-task-views/ctv#48]

**Comment by zeileis** [comment]
Di @dicook, thanks also for this idea. Given the title I think that this might also be a task view with a rather clear scope. It would be great if you could flesh out the proposal as you did for the other ones so that we can discuss it in more detail.

**Comment by zeileis** [comment]
Di @dicook, given that there was never a worked out proposal, I will close this issue. Maybe this can be revisited in the future, possibly after getting one of the other graphics-related task views off the ground.
