### ISSUE TITLE
CRAN task view proposal: Omics

### ISSUE THREAD

**Issue by julieaubert** [cran-task-views/ctv#50]
**Scope:** In this task view, we propose to focus on the most important CRAN packages dedicated to genomics data, which have been published more than one year ago and are regularly updated. A few additional packages from Bioconductor are included, not looking for an exhaustive description but pointing to the must-see packages or to packages focused on omics not well covered by CRAN packages.
We propose the following structure 
- Annotation and Databases
- Genomics
- Transcriptomics
- Proteomics
- Metabolomics
- Other omics
- Multiple omics
- Specific tasks
- Specific application fields
-
**Packages:** 
We include packages, such as biomartr, WebGestaltR, GenomicTools.fileHandler, Seurat, pagoda2, ChemoSpec, wrProteo, aLFQ, o2plsda, PMA, WGCNA, GeneNet.
Our proposal is available in the following [github repo](https://github.com/julieaubert/omicstv/blob/main/Omics.md) 

**Overlap:** The first idea was to create a task view on "Genetics and Genomics", but this ctv seems to be too wide and we decided to split it in two parts : Omics corresponding to this proposal and Genetics which needs to find its maintainer. Complementary information might also be found in r view("Phylogenetics"), r view("MachineLearning"), r view("Agriculture") or r view("MissingData") task views for some specific tasks or specific applications.
**Maintainers:** Julie Aubert, Toby Dylan Hocking, Nathalie Vialaneix

**Comment by jpiaskowski** [comment]
Hello, as one of the maintainers of the Agriculture task view, I don't see any overlap with ours because we only include applied statistical genetics packages. 

I'm not on the CRAN task view committee, but as a user, it would be helpful if the scope was more clearly delineated. The title is "omics" and the sub-headings fit that, but the scope indicates only "genomics".

**Comment by julieaubert** [comment]
Hello Julia,
thanks you for your advice. I will replaced in the text genomics with omics less restrictive and will modify the scope with
"The term omics concern various biological disciplines ending with the suffix -omics, such as genomics, proteomics, metabolomics, transcriptomics. In this task view, we focus on
the most important CRAN packages dedicated to omics data analysis, ..."

**Comment by zeileis** [comment]
Julie @julieaubert et al., thank you for this very welcome and thorough task view proposal! Apologies for the late response, I didn't get round earlier to have a closer look.

By and large, I think this is almost ready to go. I just have a couple of comments in the same vein as Julia @jpiaskowski concerning the title and scope:

- Expand `topic` in header, possibly to: Genomics, Proteomics, Metabolomics, Transcriptomics, and Other Omics
- I think it's a bit weird if the first intro paragraph starts with a description of Bioconductor. Instead, I would rearrange the paragraph a bit: start with explaining the "omics" title, the CRAN focus, and then the relationship to Bioconductor.
- There is a bit of explanation of the scope of the task view but a few more details on which packages should go in or stay out might be useful.
- Do not refer to the task view as "the Genomics task view". I guess that "this task view" would be easier to understand or "Omics task view" if you want to use the official title.

Additionally, I noticed a few formatting details:

- Some bullet points like _Cell trajectories:_ or _Protein structure and sequence:_ seem to end in a backslash that is not necessary.
- The "MaxQuant" link does not seem correctly formatted with some hanging parentheses.
- The bullet point _single-cell protein data (CITE-seq):_ should start with a capital _S_.
- Is the hyphen in "High dimensional data - regularization" necessary? I would probably just omit it.

If you address these, I think that the task view is ready for release.

**Comment by zeileis** [comment]
To officially move forward, we need the endorsement of three task view editors. I'm in favor, anyone else: @davidjohannesmeyer @eddelbuettel @rociojoo @rsbivand ? A "thumbs up" for this comment would be sufficient or you can comment below. (I have excluded @tuxette from the list above because I think she would prefer not to have to vote on her own co-proposal.)

**Comment by tuxette** [comment]
@zeileis : I confirm that I don't want to have to vote ;) And thank you for the feedback!

**Comment by willgearty** [comment]
Glad to see an -omics task view finally come together! I'm the lead maintainer of the Phylogenetics task view, so please let me know how we can help better connect the two task views!

**Comment by zeileis** [comment]
Thanks for the update, Julie @julieaubert, this looks good to me and I think we should officially publish the task view now. David @davidjohannesmeyer, Dirk @eddelbuettel, Rocío @rociojoo, Roger @rsbivand, does this have your support? Again, a thumbs up is sufficient.

**Comment by tuxette** [comment]
Thanks @willgearty ! I don't think that there is overlap with the phylogenetics TV: we have been careful not to include packages related to phylogenetics. I might send you a list of packages that we have excluded and related to phylogenetics if you want to take a look at it. We are linking the phylogenetics TV in our TV so this would be great (and make sense), were you to do the reverse. Thanks again: your feedback is appreciated!

**Comment by zeileis** [comment]
Thanks for the transfer! I now set everything up at: https://github.com/cran-task-views/Omics
I completed the meta-information, added a README, and did a few small touch-ups (see logs). You are the "Admin" for this repository, Toby is a "Maintainer", and Nathalie is by definition an "Admin" like all of the CRAN Task View Editors.
Please have another look at the repository. If you agree that everything is ready, I will do the CRAN release.

**Comment by julieaubert** [comment]
Thanks @zeileis. I corrected a remaining typo. Everything looks good for me. Let's go

**Comment by zeileis** [comment]
Oh, and I forgot to say: Thank you, Julie @julieaubert, Toby @tdhock, and Nathalie @tuxette, for putting this togeter. It's great to see this finally on CRAN. 🚀

**Comment by willgearty** [comment]
I've added a reference to the new Omics task view in the Phylogenetics task view!

**Comment by zeileis** [comment]
Excellent, thanks! I've updated CRAN correspondingly.
_(Note: Before, I just changed the version/date to use a two-digit month and day.)_
