### ISSUE TITLE
Maintenance guidelines for CRAN task views

### ISSUE THREAD

**Issue by zeileis** [cran-task-views/ctv#52]
Up to now the official CRAN Task View Initiative provides documentation on [proposing new task views](https://github.com/cran-task-views/ctv/blob/main/Proposal.md) as well as [technical documentation](https://github.com/cran-task-views/ctv/blob/main/Documentation.md) of the Markdown-based format. However, guidelines for the (teams of co-)maintainers were lacking so far.

Therefore, I have just added a first draft of some [maintenance guidelines](https://github.com/cran-task-views/ctv/blob/main/Maintenance.md) which are not mentioned in the official README, yet. I tried to cover some frequently asked questions that we get from new maintainers when we approved their proposals. Also I included some of the questions that have been discussed in the GitHub issues of this repository, specifically with respect to dealing with CRAN archivals.

Are there any additions, suggestions, comments, etc.? Specifically from the CRAN Task View Editors (@davidjohannesmeyer @eddelbuettel @tuxette @rsbivand) or any of the current task view maintainers? Feedback from other users is also welcome, of course.

**Comment by jpiaskowski** [comment]
This is really nice. It might be also useful to indicate to expect checks from @statmath-it so maintainers are not surprised or confused.

**Comment by zeileis** [comment]
Thanks, Julia! This is in the item "CRAN support" in the section "CRAN package archivals". Or do you feel that there should be more/different explanations of this?

**Comment by rsbivand** [comment]
Looks helpful, and is as clear as possible. Will the archiving of packages generate issues as trialled last year?

**Comment by zeileis** [comment]
Yes, after 60+ days. Kurt is still triggering this manually from time to time. But I'm trying to push him gently towards more frequent and possibly more automated reports.

**Comment by zeileis** [comment]
Some of the maintainers of the newly approved task views have asked about several of these pieces of information. So rather than re-writing this in various issues, I thought I would put it into a central document. It might help at least some of the task view maintainers...

**Comment by eddelbuettel** [comment]
I was referring specifically to the Vienna-shaped windmill.  I have not made any comment about your .md files.

**Comment by zeileis** [comment]
Oh well, let's see where we get. Vienna wasn't built in a day.

**Comment by eddelbuettel** [comment]
I love them with all my heart and have worked with them for twenty-plus years but as in any long-lasting relationship you cannot help but feel helpless and worn out from time to time.  :wink:

**Comment by tuxette** [comment]
I read the .md file and have no comment other than: thank you, very useful!

**Comment by zeileis** [comment]
Thanks! As no one had major concerns so far, I've linked this now in the README as well (and did some smaller improvements). If anyone still has further feedback, this is still welcome and can be incorporated.

**Comment by zeileis** [comment]
Feedback is still welcome but as there were no further comments I'm closing this issue now.
