### ISSUE TITLE
Content Section on Task Views.

### ISSUE THREAD

**Issue by hwborchers** [cran-task-views/ctv#55]
I wanted to add a content section to the Optimization Task View.
I tried to recreate what I found on the "ExtremeValues" TV.
That is, I defined links as

    CONTENTS
    * [Optimization Infrastructure Packages](#infrastr)
    * ...

and corresponding anchors as

    ### [Optimization Infrastructure Packages]{#infrastr}

The HTML page does recognize the links and identifies the target correctly, 
but there is no (re)action when clicking on the link.
Can someone please explain what I am doing wrong, or whether there is a better way?
Thanks.

**Comment by zeileis** [comment]
I would recommend to use the auto-generated anchor IDs (lower-case section title with spaces replaced by hyphens). I have just modified the .md for your task view correspondingly and updated the web page.
