### ISSUE TITLE
CRAN Task View: Chemometrics and Computational Physics

### ISSUE THREAD

**Issue by uskovgs** [cran-task-views/ctv#62]
Hi,

I would like to suggest adding my R package [panstarrs](https://cran.r-project.org/package=panstarrs) to the "Astronomy and Astrophysics" section. I believe it would be a valuable addition.

Would it be possible to include it in the appropriate section?

--
Best regards,

Grigory

**Comment by zeileis** [comment]
Thanks for this suggestion. However, you should make it in the issues of the ChemPhys task view and not here: https://github.com/cran-task-views/ChemPhys/issues
