### ISSUE TITLE
Retirement of Multivariate task view

### ISSUE THREAD

**Issue by zeileis** [cran-task-views/ctv#9]
The [Multivariate task view](https://CRAN.R-project.org/view=Multivariate) has been de facto unmaintained for quite a while now. It is also a task view that was useful when it was established but turned out to be too broad to be maintainable. We have made a couple of efforts of finding new maintainers that could give the task view a sharper focus and carry on the maintenance. An idea would have been to only cover those multivariate methods that would be in standard text books on "multivariate analysis". But all of these attempts turned out to be unsuccessful eventually.

Therefore, I propose to also retire this task view on R-Forge before the migration to GitHub - unless there are any objections from the other editors.

**Comment by rociojoo** [comment]
No objections on my side.

**Comment by zeileis** [comment]
Retired on CRAN now.
